<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //a[text()='Logout']' (tried for 3 second(s) with 500 milliseconds interval)]]>
    </line>
    <line>
      <![CDATA[HomePage is NOT displayed]]>
    </line>
  </reporter-output>
  <suite started-at="2024-12-17T10:50:37 IST" name="Default suite" finished-at="2024-12-17T10:50:55 IST" duration-ms="17794">
    <groups>
    </groups>
    <test started-at="2024-12-17T10:50:37 IST" name="Default test" finished-at="2024-12-17T10:50:55 IST" duration-ms="17794">
      <class name="scripts.ValidLogIn">
        <test-method is-config="true" signature="createReport()[pri:0, instance:scripts.ValidLogIn@1a677343]" started-at="2024-12-17T10:50:37 IST" name="createReport" finished-at="2024-12-17T10:50:37 IST" duration-ms="487" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createReport -->
        <test-method is-config="true" signature="preCondition(java.lang.reflect.Method)[pri:0, instance:scripts.ValidLogIn@1a677343]" started-at="2024-12-17T10:50:37 IST" name="preCondition" finished-at="2024-12-17T10:50:42 IST" duration-ms="4509" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void scripts.ValidLogIn.testValidLogin()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method signature="testValidLogin()[pri:1, instance:scripts.ValidLogIn@1a677343]" started-at="2024-12-17T10:50:42 IST" name="testValidLogin" finished-at="2024-12-17T10:50:54 IST" duration-ms="12472" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at scripts.ValidLogIn.testValidLogin(ValidLogIn.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //a[text()='Logout']' (tried for 3 second(s) with 500 milliseconds interval)]]>
            </line>
            <line>
              <![CDATA[HomePage is NOT displayed]]>
            </line>
          </reporter-output>
        </test-method> <!-- testValidLogin -->
        <test-method is-config="true" signature="postCondition(org.testng.ITestResult)[pri:0, instance:scripts.ValidLogIn@1a677343]" started-at="2024-12-17T10:50:54 IST" name="postCondition" finished-at="2024-12-17T10:50:55 IST" duration-ms="730" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testValidLogin status=FAILURE method=ValidLogIn.testValidLogin()[pri:1, instance:scripts.ValidLogIn@1a677343] output=Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //a[text()='Logout']' (tried for 3 second(s) with 500 milliseconds interval)]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method is-config="true" signature="publishReport()[pri:0, instance:scripts.ValidLogIn@1a677343]" started-at="2024-12-17T10:50:55 IST" name="publishReport" finished-at="2024-12-17T10:50:56 IST" duration-ms="450" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- publishReport -->
      </class> <!-- scripts.ValidLogIn -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
